[workspace]
authors = ["Ayush Thakur <ayushthakur385@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "micromojograd"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = "mojo run -I . tests/test_engine.mojo"

[dependencies]
mojo = ">=1.0.0b2.dev2026052306,<2"
